"""add_public_url_and_stopped_at

Revision ID: b93498559ecb
Revises: 932c838c3254
Create Date: 2026-06-24 16:44:47.522602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93498559ecb'
down_revision: Union[str, None] = '932c838c3254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('public_url', sa.String(length=255), nullable=True))
    op.add_column('deployments', sa.Column('stopped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'stopped_at')
    op.drop_column('deployments', 'public_url')
    # ### end Alembic commands ###
